version: "3.3"

################# !!!IMPORTANT!!! #################
# If you are using this script and it appears     #
# that you cannot connect to kafka, please add    #
# the following to you hosts file:                #
# > 127.0.0.1       kafka                         #
# This will change request from                   #
#    "kafka"                                      #
# to                                              #
#    "localhost"                                  #
# For linux/mac, you can use this command:        #
# > nano /etc/hosts                               #
# For windoof you'll have to find out             #
###################################################


services:
  zookeeper:
    image: wurstmeister/zookeeper
    ports:
      - "2181"
    hostname: zookeeper
  kafka:
    image: wurstmeister/kafka
    ports:
      - "9093:9093"
    hostname: kafka
    environment:
      KAFKA_CREATE_TOPICS: "
        some-incoming-topic:3:1,
        some-outgoing-topic:3:1,
      " # <topic>:<partition>:<replicas>
      KAFKA_AUTO_CREATE_TOPICS_ENABLE: 'false' # should automatically create topics if they are requested?
      KAFKA_ADVERTISED_LISTENERS: INSIDE://kafka:9092,OUTSIDE://kafka:9093
      KAFKA_LISTENERS: INSIDE://:9092,OUTSIDE://:9093
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: INSIDE:PLAINTEXT,OUTSIDE:PLAINTEXT
      KAFKA_INTER_BROKER_LISTENER_NAME: INSIDE
      KAFKA_ADVERTISED_HOST_NAME: kafka # docker-machine ip
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
    depends_on:
      - "zookeeper"